[package]
name = "cosmic-ext-mini-taskmanager"
version = "1.3.0"
edition = "2024"
license = "MIT"
description = "Native Mini Task Manager applet for the COSMIC desktop"
repository = "https://github.com/Kai-J-G/cosmic-ext-mini-taskmanager"

[dependencies]
serde = { version = "1", features = ["derive"] }
libc = "0.2"
sysinfo = "0.33"
i18n-embed = { version = "0.16", features = ["fluent-system", "desktop-requester"] }
i18n-embed-fl = "0.10"
rust-embed = "8"

[dependencies.libcosmic]
git = "https://github.com/pop-os/libcosmic"
default-features = false
features = ["applet", "applet-token", "dbus-config", "multi-window", "tokio", "wayland"]

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
strip = true
